services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digitalhub_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - digitalhub
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    container_name: digitalhub_nginx
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - digitalhub

networks:
  digitalhub:
    driver: bridge